// <auto-generated />
namespace FProy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class listjuegos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(listjuegos));
        
        string IMigrationMetadata.Id
        {
            get { return "201512011619547_list-juegos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
